name: pc
version: '20-0.4'
type: gadget
base: core20
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
confinement: strict
grade: stable
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    build-snaps: [snapd/latest/edge]
    stage-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed
      - sbsigntool
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]
  prepare-device:
    plugin: nil
    override-build: |
      echo "Building the 'prepare-device' hook ..."

      if [ -z "${MODEL_APIKEY}" ]; then
        echo "Please define MODEL_APIKEY for building this gadget."
        exit 1
      fi

      mkdir -p snap/hooks/

      cat << EOF > snap/hooks/prepare-device
      #!/bin/sh -ux
      mkdir -p \$SNAP_COMMON
      exec >> \$SNAP_COMMON/prepare-device-hook.log 2>&1
      product_serial=\$(date -Is)
      echo "product_serial:[\$product_serial]"
      snapctl set registration.proposed-serial="\"\${product_serial}\""
      snapctl set device-service.url="https://serial-vault-partners.canonical.com/v1/"
      snapctl set device-service.headers='{"api-key": "${MODEL_APIKEY}"}'
      EOF

      chmod +x snap/hooks/prepare-device
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/snap/hooks
      cp snap/hooks/prepare-device ${SNAPCRAFT_PART_INSTALL}/snap/hooks
