name: greggs-bugra-gadget
version: '20-0.4'
type: gadget
base: core20
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
confinement: strict
grade: stable
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    build-snaps: [snapd/latest/edge]
    stage-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed
      - sbsigntool
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]
  shim-signed-snappy-dev:
    plugin: nil
    source: .
    override-build: |
      PACKAGES="http://ppa.launchpad.net/snappy-dev/image/ubuntu/dists/focal/main/binary-amd64/Packages.gz"
      PKGPATH="$(wget -q -O- $PACKAGES|zcat|grep Filename |\
                         grep shim | grep -ve lpae|tail -1| sed 's/^Filename: //')"
      wget http://ppa.launchpad.net/snappy-dev/image/ubuntu/$PKGPATH
      dpkg -x $(basename $PKGPATH) unpack/
      cp unpack/usr/lib/shim/shimx64.efi.signed $SNAPCRAFT_PART_INSTALL/shim.efi.signed
      rm -rf unpack
  prepare-device:
    plugin: nil
    override-build: |
      echo "Building the 'prepare-device' hook ..."

      mkdir -p snap/hooks/

      cat << EOF > snap/hooks/prepare-device
      #!/bin/sh -ux
      mkdir -p \$SNAP_COMMON
      exec >> \$SNAP_COMMON/prepare-device-hook.log 2>&1
      product_serial=\$(date -Is)
      echo "product_serial:[\$product_serial]"
      snapctl set registration.proposed-serial="\"\${product_serial}\""
      EOF

      chmod +x snap/hooks/prepare-device
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/snap/hooks
      cp snap/hooks/prepare-device ${SNAPCRAFT_PART_INSTALL}/snap/hooks
